In [1]:
import pydataset

In [12]:
datasets = list(pydataset.data().dataset_id)

In [19]:
long_datasets={}
for dataset in datasets:
    if len(pydataset.data(dataset)) > 10000:
        long_datasets[dataset]= pydataset.data(dataset)
        print(dataset)

Vocab
rwm
rwm5yr
BudgetFood
CPSch3
DoctorContacts
HI
Tuna
VietNamI
hr1420
mhtdata
diamonds
movies
baseball
Bundesliga
rain
InstEval

In [27]:
long_datasets['rwm5yr']

,id,docvis,hospvis,year,edlevel,age,outwork,female,married,kids,hhninc,educ,self,edlevel1,edlevel2,edlevel3,edlevel4
1,1,1,0,1984,3,54,0,0,1,0,3.050000,15.00000,0,0,0,1,0
2,1,0,0,1985,3,55,0,0,1,0,4.510050,15.00000,0,0,0,1,0
3,1,0,0,1986,3,56,0,0,1,0,3.500000,15.00000,0,0,0,1,0
4,2,0,0,1984,1,44,1,1,1,0,3.050000,9.00000,0,1,0,0,0
5,2,1,0,1985,1,45,1,1,1,0,3.182779,9.00000,0,1,0,0,0
6,2,2,0,1986,1,46,1,1,1,0,3.500000,9.00000,0,1,0,0,0
7,2,1,0,1988,1,48,1,1,1,0,3.530501,9.00000,0,1,0,0,0
8,3,0,0,1984,1,58,1,1,0,0,1.434000,11.00000,0,1,0,0,0
9,3,0,0,1986,1,60,1,1,0,0,3.000000,11.00000,0,1,0,0,0
10,3,10,0,1987,1,61,1,1,0,0,1.100000,11.00000,0,1,0,0,0
11,3,3,0,1988,1,62,1,1,0,0,1.000000,11.00000,0,1,0,0,0
12,4,4,0,1985,4,29,0,1,0,0,1.300000,18.00000,0,0,0,0,1
13,5,1,0,1987,1,27,1,0,0,0,0.650000,11.81824,0,1,0,0,0
14,5,2,0,1988,1,28,1,0,0,0,0.600000,11.81824,0,1,0,0,0
15,6,2,0,1985,1,25,0,0,0,1,1.600000,9.00000,0,1,0,0,0
16,6,3,1,1986,1,26,0,0,1,1,3.000000,9.00000,0,1,0,0,0
17,6,0,0,1987,1,27,0,0,1,1,3.000000,9.00000,0,1,0,0,0
18,6,1,0,1988,1,28,0,0,1,1,2.000000,9.00000,0,1,0,0,0
19,7,0,0,1987,1,26,0,1,1,1,3.000000,10.00000,0,1,0,0,0
20,7,0,0,1988,1,27,1,1,1,1,2.000000,10.00000,0,1,0,0,0
21,8,7,2,1984,1,64,0,0,0,0,1.500000,10.50000,0,1,0,0,0
22,9,6,0,1984,3,30,1,0,0,0,2.400000,13.00000,0,0,0,1,0
23,9,7,0,1987,3,33,0,0,0,0,2.650000,13.00000,0,0,0,1,0
24,9,0,0,1988,3,34,0,0,1,1,6.000000,13.00000,0,0,0,1,0
25,10,0,0,1988,4,30,0,1,0,0,3.600000,18.00000,0,0,0,0,1
26,11,0,0,1988,1,37,0,1,0,0,1.800000,10.50000,0,1,0,0,0
27,12,0,0,1986,1,43,0,1,0,0,3.100000,9.00000,0,1,0,0,0
28,12,0,1,1988,1,45,0,1,0,0,4.000000,9.00000,0,1,0,0,0
29,13,9,0,1984,3,26,1,0,0,0,1.050000,13.00000,0,0,0,1,0
30,13,0,0,1988,4,30,1,0,0,0,1.200000,18.00000,0,0,0,0,1
31,14,0,0,1984,3,36,0,0,0,1,2.000000,15.00000,0,0,0,1,0
32,14,0,0,1985,3,37,0,0,0,1,3.100000,15.00000,0,0,0,1,0
33,14,0,0,1986,3,38,0,0,0,1,3.000000,15.00000,0,0,0,1,0
34,14,0,0,1987,3,39,1,0,1,1,2.900000,15.00000,0,0,0,1,0
35,14,2,0,1988,3,40,0,0,1,1,3.500000,15.00000,0,0,0,1,0
36,15,1,0,1988,1,32,0,1,1,1,3.500000,11.44142,0,1,0,0,0
37,16,0,0,1984,1,36,0,1,0,1,1.700000,10.50000,0,1,0,0,0
38,16,4,0,1985,1,37,0,1,0,1,2.100000,10.50000,0,1,0,0,0
39,16,0,0,1986,1,38,0,1,0,1,2.600000,10.50000,0,1,0,0,0
40,16,0,0,1988,1,40,0,1,0,0,2.000000,10.50000,0,1,0,0,0
41,17,38,0,1985,1,57,0,0,1,0,2.313000,10.50000,0,1,0,0,0
42,17,2,0,1986,1,58,0,0,1,0,2.350000,10.50000,0,1,0,0,0
43,17,0,0,1987,1,59,0,0,1,0,2.340000,10.50000,0,1,0,0,0
44,17,4,0,1988,1,60,0,0,1,0,2.400000,10.50000,0,1,0,0,0
45,18,62,2,1984,1,57,1,1,1,0,2.300000,10.50000,0,1,0,0,0
46,18,13,1,1985,1,58,1,1,1,0,2.313000,10.50000,0,1,0,0,0
47,18,26,0,1986,1,59,1,1,1,0,2.350000,10.50000,0,1,0,0,0
48,19,2,0,1984,1,37,0,0,1,1,2.000000,11.50000,0,1,0,0,0
49,19,2,0,1985,1,38,0,0,0,1,2.000000,11.50000,0,1,0,0,0
50,19,2,0,1986,1,39,0,0,0,1,2.500000,11.50000,0,1,0,0,0
51,19,3,0,1987,1,40,0,0,0,1,2.700000,11.50000,0,1,0,0,0
52,19,1,0,1988,1,41,0,0,0,1,3.800000,11.50000,0,1,0,0,0
53,20,2,0,1984,3,35,1,1,1,1,2.000000,14.50000,0,0,0,1,0
54,20,4,0,1986,3,37,1,1,0,1,2.500000,14.50000,0,0,0,1,0
55,20,4,0,1987,3,38,1,1,0,1,2.700000,14.50000,0,0,0,1,0
56,20,0,0,1988,3,39,0,1,0,1,3.800000,14.50000,0,0,0,1,0
57,21,0,0,1985,4,39,0,0,1,1,6.400000,18.00000,0,0,0,0,1
58,21,0,0,1986,4,40,0,0,0,1,3.600000,18.00000,0,0,0,0,1
59,21,0,0,1988,4,42,0,0,0,1,3.900000,18.00000,0,0,0,0,1
60,22,0,0,1984,4,38,0,1,1,1,5.500000,18.00000,0,0,0,0,1
61,22,0,0,1985,4,39,0,1,1,1,6.400000,18.00000,0,0,0,0,1
62,22,0,0,1986,4,40,0,1,0,0,2.200000,18.00000,0,0,0,0,1
63,22,0,0,1987,4,41,0,1,0,0,3.000000,18.00000,0,0,0,0,1
64,22,0,0,1988,4,42,0,1,0,0,3.200000,18.00000,0,0,0,0,1
65,23,0,0,1985,1,48,0,0,1,0,5.500000,11.50000,0,1,0,0,0
66,24,0,0,1984,1,46,0,1,1,0,3.941831,11.50000,0,1,0,0,0
67,25,5,0,1985,4,61,1,1,0,0,1.282000,17.00000,0,0,0,0,1
68,25,2,0,1986,4,62,1,1,0,0,0.742000,17.00000,0,0,0,0,1
69,25,6,0,1987,4,63,1,1,0,0,1.258000,17.00000,0,0,0,0,1
70,25,3,0,1988,4,64,1,1,0,0,0.881000,17.00000,0,0,0,0,1
71,26,0,0,1984,4,32,0,0,0,0,0.800000,18.00000,1,0,0,0,1
72,26,0,0,1985,4,33,0,0,1,0,4.520623,18.00000,1,0,0,0,1
73,26,0,0,1986,4,34,0,0,0,0,1.200000,18.00000,1,0,0,0,1
74,26,1,0,1988,4,36,0,0,0,0,1.100000,18.00000,1,0,0,0,1
75,27,0,0,1987,3,30,0,0,0,0,2.600000,13.50000,0,0,0,1,0
76,27,0,0,1988,3,31,0,0,0,0,2.650000,13.50000,0,0,0,1,0
77,28,0,0,1984,1,37,1,0,0,0,1.012000,10.50000,0,1,0,0,0
78,28,0,0,1986,1,39,0,0,0,0,4.000000,10.50000,0,1,0,0,0
79,28,0,0,1987,1,40,0,0,1,0,4.100000,10.50000,0,1,0,0,0
80,28,0,0,1988,1,41,0,0,1,0,4.100000,10.50000,0,1,0,0,0
81,29,4,0,1987,1,31,0,1,1,0,4.100000,11.50000,0,1,0,0,0
82,29,3,0,1988,1,32,0,1,1,0,4.100000,11.50000,0,1,0,0,0
83,30,0,0,1984,1,52,0,0,0,0,1.900000,11.00000,0,1,0,0,0
84,30,10,0,1988,1,56,0,0,0,0,2.089000,11.00000,0,1,0,0,0
85,31,0,0,1986,1,39,0,0,1,1,4.200000,10.50000,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19525,6896,0,0,1988,1,56,0,0,1,0,4.038000,9.00000,1,1,0,0,0
19526,6898,4,0,1986,1,25,1,1,0,0,1.161985,7.00000,0,1,0,0,0
19527,6898,0,0,1987,1,26,1,1,0,0,4.388000,7.00000,0,1,0,0,0
19528,6898,0,0,1988,1,27,1,1,0,0,4.038000,7.00000,0,1,0,0,0
19529,6900,4,2,1987,2,26,0,1,1,0,3.000000,12.00000,0,0,1,0,0
19530,6900,8,2,1988,2,27,1,1,1,0,2.500000,12.00000,0,0,1,0,0
19531,6901,2,0,1988,4,31,0,1,1,0,5.500000,18.00000,0,0,0,0,1
19532,6902,7,0,1986,1,26,0,1,1,0,3.400000,10.50000,0,1,0,0,0
19533,6903,0,0,1987,4,27,0,0,0,0,3.000000,18.00000,0,0,0,0,1
19534,6903,0,0,1988,4,28,0,0,0,0,4.200000,18.00000,0,0,0,0,1
19535,6904,0,0,1988,1,26,0,0,1,0,2.400000,9.00000,0,1,0,0,0
19536,6905,2,1,1986,1,26,0,0,1,0,2.800000,10.50000,0,1,0,0,0
19537,6905,1,0,1987,1,27,0,0,1,0,3.100000,10.50000,0,1,0,0,0
19538,6905,0,0,1988,1,28,0,0,1,1,2.800000,10.50000,0,1,0,0,0
19539,6906,4,1,1986,2,32,1,1,1,1,3.700000,12.00000,0,0,1,0,0
19540,6906,2,0,1987,2,33,1,1,1,1,4.000000,12.00000,0,0,1,0,0
19541,6908,1,0,1988,1,25,0,0,1,1,2.400000,11.00000,0,1,0,0,0
19542,6909,0,0,1987,1,39,0,0,1,1,2.900000,10.50000,0,1,0,0,0
19543,6909,0,0,1988,1,40,0,0,1,1,3.270000,10.50000,0,1,0,0,0
19544,6913,0,0,1986,2,28,0,0,1,1,4.000000,12.00000,0,0,1,0,0
19545,6913,2,1,1987,2,29,0,0,1,1,4.000000,12.00000,0,0,1,0,0
19546,6913,1,1,1988,2,30,0,0,1,1,3.200000,12.00000,0,0,1,0,0
19547,6915,0,0,1986,2,26,0,0,0,0,4.500000,12.00000,0,0,1,0,0
19548,6915,0,0,1987,2,27,0,0,0,0,4.500000,12.00000,0,0,1,0,0
19549,6916,0,0,1986,1,39,0,0,1,1,3.700000,10.50000,0,1,0,0,0
19550,6916,5,0,1987,1,40,0,0,1,1,2.200000,10.50000,0,1,0,0,0
19551,6917,4,0,1987,1,37,1,1,1,1,2.200000,11.50000,0,1,0,0,0
19552,6918,0,0,1988,1,28,0,0,1,1,2.200000,11.81824,0,1,0,0,0
19553,6919,1,0,1986,1,29,0,0,0,1,3.000000,9.00000,0,1,0,0,0
19554,6919,0,0,1987,1,30,0,0,0,1,2.700000,9.00000,0,1,0,0,0
19555,6919,0,0,1988,1,31,0,0,0,1,3.250000,9.00000,0,1,0,0,0
19556,6920,0,1,1988,1,31,0,1,0,0,6.000000,10.50000,0,1,0,0,0
19557,6923,1,0,1988,1,26,0,0,1,0,3.900000,10.50000,0,1,0,0,0
19558,6924,0,0,1987,1,26,0,0,0,0,2.450000,10.50000,0,1,0,0,0
19559,6924,0,0,1988,1,27,0,0,0,0,3.000000,10.50000,0,1,0,0,0
19560,6928,0,0,1987,1,25,0,0,0,0,2.800000,10.50000,0,1,0,0,0
19561,6928,0,0,1988,1,26,0,0,1,0,3.500000,10.50000,0,1,0,0,0
19562,6929,1,0,1988,1,27,0,0,0,0,4.000000,10.50000,0,1,0,0,0
19563,6935,3,0,1988,3,27,1,0,0,0,1.100000,13.00000,0,0,0,1,0
19564,6936,0,0,1987,1,25,0,0,1,0,3.250000,11.50000,0,1,0,0,0
19565,6936,0,0,1988,1,26,0,0,1,1,2.350000,11.50000,0,1,0,0,0
19566,6940,0,0,1988,3,32,0,0,1,0,3.850000,14.00000,0,0,0,1,0
19567,6944,0,1,1988,1,28,1,0,0,0,2.200000,10.50000,0,1,0,0,0
19568,6945,2,0,1988,1,29,0,0,1,0,1.100000,7.00000,0,1,0,0,0
19569,6946,0,0,1987,1,26,0,0,1,0,3.600000,10.50000,0,1,0,0,0
19570,6946,0,0,1988,1,27,0,0,1,0,3.500000,10.50000,0,1,0,0,0
19571,6947,0,0,1988,1,28,0,0,0,0,2.200000,10.50000,0,1,0,0,0
19572,6948,1,0,1987,1,27,0,0,0,0,2.481012,10.50000,0,1,0,0,0
19573,6948,0,0,1988,1,28,0,0,0,0,2.200000,10.50000,0,1,0,0,0
19574,6949,0,0,1987,1,35,0,0,1,1,2.100000,11.00000,0,1,0,0,0
19575,6949,1,0,1988,1,36,0,0,1,1,2.800000,11.00000,0,1,0,0,0
19576,6953,2,0,1988,4,28,0,0,1,1,1.700000,18.00000,0,0,0,0,1
19577,6955,7,0,1987,2,28,0,0,1,0,2.200000,12.00000,0,0,1,0,0
19578,6955,1,0,1988,2,29,0,0,1,1,3.700000,12.00000,0,0,1,0,0
19579,6957,0,0,1987,1,25,0,0,0,0,2.670000,10.50000,0,1,0,0,0
19580,6957,0,0,1988,1,26,0,0,1,0,3.500000,10.50000,0,1,0,0,0
19581,6958,0,1,1988,4,35,0,1,1,1,3.100000,18.00000,0,0,0,0,1
19582,6960,2,0,1987,1,26,0,0,0,0,2.850000,11.50000,0,1,0,0,0
19583,6960,1,0,1988,1,27,0,0,0,0,3.000000,11.50000,0,1,0,0,0
19584,6962,0,0,1988,3,27,0,0,0,0,2.200000,13.50000,0,0,0,1,0
19585,6964,5,0,1987,4,47,0,0,1,1,7.000000,18.00000,0,0,0,0,1
19586,6964,5,0,1988,4,48,0,0,1,1,6.500000,18.00000,0,0,0,0,1
19587,6965,0,0,1987,1,28,0,0,1,0,2.100000,11.81824,0,1,0,0,0
19588,6965,4,0,1988,1,29,1,0,1,0,2.400000,11.81824,0,1,0,0,0
19589,6970,0,0,1988,3,27,0,0,1,1,3.000000,16.00000,0,0,0,1,0
19590,6971,4,0,1987,1,27,0,0,0,0,3.100000,10.50000,0,1,0,0,0
19591,6971,20,0,1988,1,28,1,0,0,0,1.480000,10.50000,0,1,0,0,0
19592,6976,1,0,1988,1,25,0,0,0,0,4.000000,11.50000,0,1,0,0,0
19593,6981,0,0,1988,1,31,0,0,1,1,3.200000,11.81824,0,1,0,0,0
19594,6985,5,0,1988,1,30,0,0,0,0,3.500000,11.50000,0,1,0,0,0
19595,6986,0,0,1988,4,29,0,0,0,0,4.800000,18.00000,0,0,0,0,1
19596,6987,2,0,1988,1,52,0,0,0,0,2.100000,9.00000,0,1,0,0,0
19597,6990,3,1,1988,3,33,0,0,0,0,3.770000,13.50000,0,0,0,1,0
19598,6991,4,0,1988,1,47,0,1,0,0,3.700000,10.50000,0,1,0,0,0
19599,6995,0,0,1988,1,26,0,0,0,0,3.700000,11.00000,0,1,0,0,0
19600,6999,1,0,1988,1,27,0,0,0,0,3.250000,10.50000,0,1,0,0,0
19601,7005,0,0,1988,3,28,0,0,0,0,3.000000,14.50000,0,0,0,1,0
19602,7007,3,0,1988,3,27,0,0,1,0,4.000000,15.00000,0,0,0,1,0
19603,7008,1,0,1988,3,25,0,1,0,0,4.000000,13.50000,0,0,0,1,0
19604,7011,3,0,1988,1,27,0,1,1,0,3.700000,11.50000,0,1,0,0,0
19605,7015,1,0,1988,1,27,0,1,1,0,3.800000,11.00000,0,1,0,0,0
19606,7016,6,0,1988,1,31,0,0,1,0,2.067000,11.81824,0,1,0,0,0
19607,7023,0,0,1988,1,31,0,0,1,1,2.600000,11.00000,0,1,0,0,0
19608,7026,2,0,1988,1,26,0,0,1,0,3.000000,10.50000,0,1,0,0,0
19609,7028,2,0,1988,1,30,0,1,0,0,0.990000,10.50000,0,1,0,0,0

In [31]:
pydataset.data('rwm5yr',1)

rwm5yr

PyDataset Documentation (adopted from R Documentation. The displayed examples are in R)

## rwm5yr

### Description

German health registry for the years 1984-1988. Health information for years
immediately prior to health reform.

### Usage

    data(rwm5yr)

### Format

A data frame with 19,609 observations on the following 17 variables.

`id`

patient ID (1=7028)

`docvis`

number of visits to doctor during year (0-121)

`hospvis`

number of days in hospital during year (0-51)

`year`

year; (categorical: 1984, 1985, 1986, 1987, 1988)

`edlevel`

educational level (categorical: 1-4)

`age`

age: 25-64

`outwork`

out of work=1; 0=working

`female`

female=1; 0=male

`married`

married=1; 0=not married

`kids`

have children=1; no children=0

`hhninc`

household yearly income in marks (in Marks)

`educ`

years of formal education (7-18)

`self`

self-employed=1; not self employed=0

`edlevel1`

(1/0) not high school graduate

`edlevel2`

(1/0) high school graduate

`edlevel3`

(1/0) university/college

`edlevel4`

(1/0) graduate school

### Details

rwm5yr is saved as a data frame. Count models typically use docvis as response
variable. 0 counts are included

### Source

German Health Reform Registry, years pre-reform 1984-1988, in Hilbe and Greene
(2007)

### References

Hilbe, Joseph M (2014), Modeling Count Data, Cambridge University Press Hilbe,
Joseph M (2011), Negative Binomial Regression, Cambridge University Press
Hilbe, J. and W. Greene (2008). Count Response Regression Models, in ed. C.R.
Rao, J.P Miller, and D.C. Rao, Epidemiology and Medical Statistics, Elsevier
Handbook of Statistics Series. London, UK: Elsevier.

### Examples

    library(MASS)
    data(rwm5yr)
    glmrp <- glm(docvis ~ outwork + female + age + factor(edlevel), family=poisson, data=rwm5yr)
    summary(glmrp)
    exp(coef(glmrp))
    ## Not run:
    library(msme)
    nb2 <- nbinomial(docvis ~ outwork + female + age + factor(edlevel), data=rwm5yr)
    summary(nb2)
    exp(coef(nb2))
    glmrnb <- glm.nb(docvis ~ outwork + female + age + factor(edlevel), data=rwm5yr)
    summary(glmrnb)
    exp(coef(glmrnb))
    ## End(Not run)

In [ ]:
text = ""

post = {"text": "{0}".format(text)}

try:
    json_data = json.dumps(post)
    req = request.Request("https://hooks.slack.com/services/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",
                              data=json_data.encode('ascii'),
                              headers={'Content-Type': 'application/json'}) 
    resp = request.urlopen(req)
except Exception as em:
    print("EXCEPTION: " + str(em))